### ISSUE TITLE
[BUG][Enhancement] Backup corrupts vault | New Settings options

### ISSUE THREAD

**Issue by HarriBuh** [Kin69/EasyNotes#105] opened 2024-07-16 13:42 UTC
## Required Information

- [x ] I’m using the latest EasyNotes version
- [ ] The device is not rooted, and nothing has been removed via ADB

### Steps to Reproduce the Bug

1. Open App

2. Click on the lock icon in the search bar to secure/encrypt all the notes with a password

(2.1 Recognise all notes are now encrypted)

3a. (NOT stopping it!) Leave the app

3b. Manually stop the app

4.Open the app again

5a. Recognise all the notes are still encrypted

5b. Recognise all the notes are now DEcrypted again

6a. Click on the lock icon

7a. Recognise all notes are now decrypted without getting asked for that password again

### Expected Behavior
The app should ask for the password before decrypting the notes, not do it without. This means encrypting the notes is worthless right now.

### Screenshots
![Screenshot_20240716-153459.png](https://github.com/user-attachments/assets/e70ee22d-f830-4a76-89ca-2c48dfa48536)

### Smartphone Information
- **Device:** Google Pixel 7
- **OS:** Android 14
- **EasyNotes Version:** 1.3

**Comment by Kin69** [comment] 2024-07-16 13:51
Does it ask for password?

**Comment by Kin69** [comment] 2024-07-16 15:34
@HarriBuh 
The lock icon does not encrypt your current notes. Instead, it opens a folder where any new notes you save will be encrypted. By default, when you open the app, it shows unencrypted notes. Clicking the lock icon again prompts for a password. If the password is correct, it will attempt to encrypt the notes in the folder.

The "Invalid encrypted data format" error occurs because the app is trying to decrypt notes that are not encrypted, or because the password is incorrect. If you have entered an encrypted subfolder without the correct password, the app may crash.

I tried replicating the issue on the same device, and it worked for me without showing the error. I need to know if you installed the app as new or migrated from an older version. If you migrated, was it from a nightly build or version 1.2.5?

**Comment by Kin69** [comment] 2024-07-16 18:39
@serrq The system supports both encrypted and unencrypted notes. To create an encrypted note, you need to do so within the vault. Regular notes are displayed upon entering the application. To view encrypted notes, you must re-enter the vault.

**Comment by Kin69** [comment] 2024-07-16 18:47
Here is tutorial how to create encrypted note:

https://github.com/user-attachments/assets/d6cb3352-39b2-46b4-841d-79b1e6378048

**Comment by Kin69** [comment] 2024-07-16 19:02
Alright, I’ll recode it, probably tomorrow. If it doesn’t get accepted by IzzyOnDroid or F-Droid, I’ll include it in version 1.3

**Comment by tsiflimagas** [comment] 2024-07-16 21:31
@Kin69 I'm not sure what are you planning on by saying you'll recode it, but if it's to make it as @serrq says, I strongly disagree. A user with proper perception will be confused if when he taps the lock icon all his notes become encrypted, because that won't be what he'll expect. It is rational as it is. You tap the lock, you're navigated to the encrypted folder. If one wants to encrypt non encrypted notes, what would make sense imo would be to add an option to move notes in the vault.

**Comment by Kin69** [comment] 2024-07-17 07:36
Yes, this feature is already available on Izziondroid, and I have no intention of removing it. The term "Vault" implies that there are both standard and vault options. By "recode," I mean adding new settings that become available once you enable the Vault feature. For example, options like "Open Vault by default" or "Encrypt current notes" would allow you to encrypt all existing notes and automatically redirect to the Vault, providing full access to Vault functionalities.

@tsiflimagas Regarding corrupted data, there is currently a bug when trying to access the vault after recovering via backup or migrating from some nightly builds.

If anyone has suggestions for improving this functionality or ideas better than adding these two settings, please let me know before the update is finalized.

**Comment by Kin69** [comment] 2024-08-09 10:37
@HarriBuh, I've completely overhauled the vault functionality to operate on a more robust logic. While the UI remains unchanged, the underlying data handling should now prevent any loss or corruption. Since I can't reproduce the error on my end, I'd appreciate it if you could test it on your device and let me know if everything works as expected. You can find the updated version in the nightly build.

**Comment by Kin69** [comment] 2024-08-10 07:57
I’ll be closing this issue as the vault functionality should now be working correctly. If anyone encounters any errors in the new version, feel free to reopen the issue.

**Closed by Kin69** 2024-08-10 07:57 UTC
Labels: bug
